"""Regenerate public synthetic supplied-key payload fixtures using independent PyCryptodome.

This is a reference generator, not a key search. All material is fixed test data.
The normal build uses the checked-in header and does not require PyCryptodome.
"""
from pathlib import Path
import sys
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root/'build/reference-libs'))
from Crypto.Cipher import AES, DES

def expand(mi):
    register=int.from_bytes(mi,'big')
    for _ in range(64):
        feedback=sum((register>>n)&1 for n in (63,61,45,37,26,14))&1
        register=((register<<1)|feedback)&((1<<64)-1)
    return mi+register.to_bytes(8,'big')

def array(data): return '{'+','.join(f'0x{x:02x}' for x in data)+'}'
lines=['// Generated by scripts/generate_privacy_vectors.py; public synthetic keys.',
       '// Independent PyCryptodome OFB, P25 MI expansion, protocol stream offsets.',
       'typedef struct { int alg; unsigned long long mi; unsigned char iv[16], p1[22], p2[14]; } privacy_vector;',
       'static const privacy_vector privacy_vectors[] = {']
plain=bytes.fromhex('112233445566778899aabb')*2
for alg,size in ((0x89,16),(0x84,32),(0x81,8)):
    for mi in (bytes.fromhex('1020304050607080'),bytes.fromhex('fedcba9876543210')):
        iv=expand(mi); key=bytes(range(size))
        stream=(DES.new(key,DES.MODE_OFB,iv=mi) if size==8 else AES.new(key,AES.MODE_OFB,iv=iv)).encrypt(bytes(240))
        offset=19 if size==8 else 27
        p1=bytes(a^b for a,b in zip(plain,stream[offset:offset+22]))
        offset=8 if size==8 else 16
        p2=bytes(a^b for a,b in zip(bytes.fromhex('11223344556677')*2,stream[offset:offset+14]))
        lines.append('{'+f'0x{alg:02x},0x{mi.hex()}ULL,{array(iv)},{array(p1)},{array(p2)}'+'},')
lines.append('};')
(root/'checks/privacy_vectors.h').write_text('\n'.join(lines)+'\n')
print('Generated six reference cases: AES-128/256 and DES with two message indicators')
