"""Public supplied-key payload references; no key search or private radio data.

PyCryptodome independently generates OFB bits. This checks the native payload
transform with an already established IV, not RF acquisition or IV signaling.
"""
from pathlib import Path
import hashlib, sys
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root/'build/reference-libs'))
from Crypto.Cipher import AES, DES
def array(data):return '{'+','.join(f'0x{x:02x}' for x in data)+'}'
def bits(data):return [(b >> j)&1 for b in data for j in range(7,-1,-1)]
def pack(data):return bytes(sum(data[i+j] << (7-j) for j in range(8)) for i in range(0,len(data),8))
lines=['// Public synthetic supplied keys; generated by scripts/generate_nxdn_vectors.py.',
       'typedef struct { int cipher; unsigned char iv[16], plain[224], encrypted[224]; } nxdn_vector;',
       'static const nxdn_vector nxdn_vectors[] = {']
for cipher in (2,3):
    for iv in (bytes.fromhex('102030405060708090a0b0c0d0e0f000'), bytes.fromhex('fedcba98765432100123456789abcdef')):
        engine=DES.new(bytes(range(8)),DES.MODE_OFB,iv=iv[:8]) if cipher==2 else AES.new(bytes(range(32)),AES.MODE_OFB,iv=iv)
        discard=8 if cipher==2 else 16
        stream=bits(engine.encrypt(bytes(240))[discard:])
        plain=[]; encrypted=[]
        for frame in range(32):
            voice=bits(hashlib.sha256(bytes([cipher,frame])).digest())[:49]
            plain.extend(pack(voice+[0]*7))
            encrypted.extend(pack([a^b for a,b in zip(voice,stream[frame*49:])]+[0]*7))
        lines.append('{'+f'{cipher},{array(iv)},{array(plain)},{array(encrypted)}'+'},')
lines.append('};')
(root/'checks/nxdn_privacy_vectors.h').write_bytes(('\n'.join(lines)+'\n').encode())
print('Generated DES/AES-256 references, two IVs, 32 voice frames each')
